version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install torch --index-url https://download.pytorch.org/whl/cpu

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

formats:
  - pdf
  - epub